name: data_market
description: TradeLens · data_market package.
version: 0.1.0
publish_to: none
resolution: workspace
environment:
  sdk: ^3.13.0
dependencies:
  core:
  domain:
  ws_client:
dev_dependencies:
  test: ^1.25.0
  very_good_analysis: ^11.0.0
