// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum OnDeviceAvailability: Int, CaseIterable {
  case available = 0
  case unsupportedDevice = 1
  case unsupportedOs = 2
  case modelNotReady = 3
  case disabled = 4
}

/// Generated class from Pigeon that represents data sent in messages.
struct OnDeviceRequest: Hashable, CustomStringConvertible {
  var system: String
  var prompt: String
  var languageCode: String
  var maxOutputChars: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> OnDeviceRequest? {
    let system = pigeonVar_list[0] as! String
    let prompt = pigeonVar_list[1] as! String
    let languageCode = pigeonVar_list[2] as! String
    let maxOutputChars = pigeonVar_list[3] as! Int64

    return OnDeviceRequest(
      system: system,
      prompt: prompt,
      languageCode: languageCode,
      maxOutputChars: maxOutputChars
    )
  }
  func toList() -> [Any?] {
    return [
      system,
      prompt,
      languageCode,
      maxOutputChars,
    ]
  }
  static func == (lhs: OnDeviceRequest, rhs: OnDeviceRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.system, rhs.system) && MessagesPigeonInternal.deepEquals(lhs.prompt, rhs.prompt) && MessagesPigeonInternal.deepEquals(lhs.languageCode, rhs.languageCode) && MessagesPigeonInternal.deepEquals(lhs.maxOutputChars, rhs.maxOutputChars)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("OnDeviceRequest")
    MessagesPigeonInternal.deepHash(value: system, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: prompt, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: languageCode, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxOutputChars, hasher: &hasher)
  }

  public var description: String {
    return "OnDeviceRequest(system: \(String(describing: system)), prompt: \(String(describing: prompt)), languageCode: \(String(describing: languageCode)), maxOutputChars: \(String(describing: maxOutputChars)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return OnDeviceAvailability(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return OnDeviceRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? OnDeviceAvailability {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? OnDeviceRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol OnDeviceLlmHostApi {
  func availability() throws -> OnDeviceAvailability
  func generate(request: OnDeviceRequest) async throws -> String
  func cancel() throws
  func describeRuntime() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class OnDeviceLlmHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `OnDeviceLlmHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: OnDeviceLlmHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let availabilityChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.on_device_llm.OnDeviceLlmHostApi.availability\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      availabilityChannel.setMessageHandler { _, reply in
        do {
          let result = try api.availability()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      availabilityChannel.setMessageHandler(nil)
    }
    let generateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.on_device_llm.OnDeviceLlmHostApi.generate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! OnDeviceRequest
        Task { @MainActor in
          do {
            let result = try await api.generate(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateChannel.setMessageHandler(nil)
    }
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.on_device_llm.OnDeviceLlmHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { _, reply in
        do {
          try api.cancel()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
    let describeRuntimeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.on_device_llm.OnDeviceLlmHostApi.describeRuntime\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      describeRuntimeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.describeRuntime()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      describeRuntimeChannel.setMessageHandler(nil)
    }
  }
}
