name: ws_client
description: TradeLens · ws_client package.
version: 0.1.0
publish_to: none
resolution: workspace
environment:
  sdk: ^3.13.0
dependencies:
  core:
dev_dependencies:
  test: ^1.25.0
  very_good_analysis: ^11.0.0
  fake_async: ^1.3.3
